' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' 1DV607 -- Object-Oriented Design and Analysis with UML
' Workshop 1: Domain Modeling
' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Created by Jonas Sjöberg (js224eh) on 2017-09-04.
' Linnaeus University
' ""js224eh@student.lnu.se""
' ""http://www.jonasjberg.com""
' ""https://github.com/jonasjberg""

@startuml
' ______________________________________________________________________________
' ____ CONFIGURATION OPTIONS ___________________________________________________
' debug flag creates a 'svek.dot' and 'svek.svg' file in ~/
' !pragma svek_trace on
allow_mixing

skinparam {
    monochrome true
    'backgroundColor transparent
    classBackgroundColor transparent
    style strictuml
}

' ______________________________________________________________________________
' ____ USECASE DIAGRAM _________________________________________________________

header
1DV607 - Workshop 1: Domain Modeling
Jonas Sjöberg <""js224eh@student.lnu.se"">
end header

title \nDomain Model #3\n(Requirements for grade 4)\nautonameow Data Model

agent Book
agent Photo
agent MeowURI
agent ISBN
agent DataField
agent Metadata
'agent PlainText
agent DataExtractor
agent Plugin
agent DataRepository
'agent Analyzer
agent FileObject

agent MetadataType
note left of MetadataType : - Title\n- Publisher\n- CreateDate

agent NameBuilder




MeowURI -> DataField : uniquely identifies
ISBN --> Book : identifies

DataField <|-- Metadata
'DataField <|-- PlainText


Metadata <|-- MetadataType

FileObject --|> Book
FileObject --|> Photo

Book "1" *-- "*" Metadata : contains
Photo "1" *-- "*" Metadata : contains

DataExtractor ..> DataField : produces
Plugin ..> DataField : produces

DataRepository <-- DataField : contains

NameBuilder <.. DataRepository : retrieves
Plugin ..> DataRepository : stores
DataExtractor ..> DataRepository : stores

'Analyzer --> DataField : analyzes

NameBuilder --> FileObject : renames
@enduml
