' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' 1DV607 -- Object-Oriented Design and Analysis with UML
' Workshop 2: Design
' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Created by Jonas Sjöberg (js224eh) on 2017-10-03.
' Linnaeus University
' ""js224eh@student.lnu.se""
' ""http://www.jonasjberg.com""
' ""https://github.com/jonasjberg""

@startuml
' ______________________________________________________________________________
' ____ CONFIGURATION OPTIONS ___________________________________________________
' debug flag creates a 'svek.dot' and 'svek.svg' file in ~/
' !pragma svek_trace on
' allow_mixing

skinparam {
    monochrome true
    'backgroundColor transparent
    classBackgroundColor transparent
    style strictuml
}

' ______________________________________________________________________________
' ____ USECASE DIAGRAM _________________________________________________________

header
1DV607 - Workshop 2: Design
Jonas Sjöberg <""js224eh@student.lnu.se"">
end header

title \nSequence Diagram\nList all Members\n

ApplicationController -> ApplicationView: get_selection_from(events)
activate ApplicationView

ApplicationController <-- ApplicationView: chosen_event
deactivate ApplicationView

activate ApplicationController

ApplicationController -> ApplicationController: event_func() (bound method)

ApplicationController -> MemberController: _list_all()
deactivate ApplicationController

MemberController -> MemberRegistry: getall()
activate MemberRegistry
MemberController <-- MemberRegistry: member_list
deactivate MemberRegistry

MemberController -> MemberView: list(member_list)
activate MemberView

MemberView -> MemberView: get_selection_from(verbosity_map)
MemberController <-- MemberView: exceptions.InvalidUserInput
MemberView -> MemberView: display(selected_verobosity)

@enduml
